#!name= 𝗔𝗹𝗹 𝗜𝗻 𝗢𝗻𝗲
#!desc= 🐰

[General]
bypass-system = true
skip-proxy = *.local, *.crashlytics.com
tun-excluded-routes = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12

[Header Rewrite]
http-request ^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/user-customization-service\/v1\/customize$ header-del if-none-match

[Map Local]
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad data-type=text data="" status-code=200

[Rule]
AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT
AND,((DOMAIN,youtubei.googleapis.com), (PROTOCOL,UDP)),REJECT

[MITM]
hostname = %APPEND% api.revenuecat.com,buy.itunes.apple.com,api-mobile.soundcloud.com,spclient.wg.spotify.com, *spclient.spotify.com,*.googlevideo.com, youtubei.googleapis.com

[Script]

# Locket
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$), requires-body=true, max-size=-1, timeout=60, script-path=https://patexiutoo.vercel.app/scripts/revenuecat.js
deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers), timeout=60, script-path=https://patexiutoo.vercel.app/scripts/deleteheader.js

————————————————————————————————————————————————————

# SoundCloud
SoundCloudGo= type=http-response,pattern=https://api-mobile.soundcloud.com/configuration/ios,requires-body=1,script-path=https://patexiutoo.vercel.app/scripts/soundcloud.js

————————————————————————————————————————————————————

# Spotify
spotify-json = type=http-request,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,requires-body=0,script-path=https://patexiutoo.vercel.app/scripts/spotify-json.js
spotify-proto = type=http-response,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-update-interval=0,script-path=https://patexiutoo.vercel.app/scripts/spotify-proto.js

————————————————————————————————————————————————————

# VSCO
vsco = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$), requires-body=true, timeout=5, script-path=https://patexiutoo.vercel.app/scripts/vsco.js
vscoo = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers(\/.*?)?$), requires-body=true, timeout=5, script-path=https://patexiutoo.vercel.app/scripts/vscoo.js

————————————————————————————————————————————————————

# YouTube
youtube.response = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/(youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch))(\?(.*))?$,requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://patexiutoo.vercel.app/scripts/youtube.js,argument="{"lyricLang":"{{{dịch lời bài hát}}","captionLang":"{{{dịch phụ đề}}}","blockUpload":{{{ẩn tải lên}}},"blockImmersive":{{{ẩn nút chọn đoạn}}},"blockShorts":{{{ẩn nút short}}},"debug":{{{bật chế độ gỡ lỗi}}}}"
