#!name= 𝗟𝗼𝗰𝗸𝗲𝘁 𝗚𝗼𝗹𝗱
#!desc= 🐰

[MITM]
hostname = %APPEND% api.revenuecat.com
[Script]
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$), requires-body=true, max-size=-1, timeout=60, script-path=https://patexiutoo.vercel.app/scripts/revenuecat.js
deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers), timeout=60, script-path=https://patexiutoo.vercel.app/scripts/deleteheader.js
