#!name= 𝗬𝗼𝘂𝗧𝘂𝗯𝗲
#!desc= 🐰

[Map Local]
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad data-type=text data="" status-code=200

[Rule]
AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT
AND,((DOMAIN,youtubei.googleapis.com), (PROTOCOL,UDP)),REJECT

[MITM]
hostname = %APPEND% *.googlevideo.com, youtubei.googleapis.com

[Script]
youtube.response = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/(youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch))(\?(.*))?$,requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://patexiutoo.vercel.app/scripts/youtube.js,argument="{"lyricLang":"{{{dịch lời bài hát}}","captionLang":"{{{dịch phụ đề}}}","blockUpload":{{{ẩn tải lên}}},"blockImmersive":{{{ẩn nút chọn đoạn}}},"blockShorts":{{{ẩn nút short}}},"debug":{{{bật chế độ gỡ lỗi}}}}"
